################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/tutorial \
src/tools/fsync \
src/tools/findoidjoins \
src/tools/entab \
src/timezone \
src/test/thread \
src/test/regress \
src/test/locale \
src/test/examples \
src/port \
src/pl/tcl \
src/pl/plpython \
src/pl/plpgsql/src \
src/pl/plperl \
src/interfaces/libpq \
src/interfaces/ecpg/test/thread \
src/interfaces/ecpg/test/sql \
src/interfaces/ecpg/test/preproc \
src/interfaces/ecpg/test/pgtypeslib \
src/interfaces/ecpg/test/expected \
src/interfaces/ecpg/test/connect \
src/interfaces/ecpg/test/compat_informix \
src/interfaces/ecpg/preproc \
src/interfaces/ecpg/pgtypeslib \
src/interfaces/ecpg/ecpglib \
src/interfaces/ecpg/compatlib \
src/bin/scripts \
src/bin/psql \
src/bin/pgevent \
src/bin/pg_resetxlog \
src/bin/pg_dump \
src/bin/pg_ctl \
src/bin/pg_controldata \
src/bin/pg_config \
src/bin/initdb \
src/backend/utils/time \
src/backend/utils/sort \
src/backend/utils/resowner \
src/backend/utils/mmgr \
src/backend/utils/misc \
src/backend/utils/mb \
src/backend/utils/mb/conversion_procs/utf8_and_win \
src/backend/utils/mb/conversion_procs/utf8_and_uhc \
src/backend/utils/mb/conversion_procs/utf8_and_sjis \
src/backend/utils/mb/conversion_procs/utf8_and_johab \
src/backend/utils/mb/conversion_procs/utf8_and_iso8859_1 \
src/backend/utils/mb/conversion_procs/utf8_and_iso8859 \
src/backend/utils/mb/conversion_procs/utf8_and_gbk \
src/backend/utils/mb/conversion_procs/utf8_and_gb18030 \
src/backend/utils/mb/conversion_procs/utf8_and_euc_tw \
src/backend/utils/mb/conversion_procs/utf8_and_euc_kr \
src/backend/utils/mb/conversion_procs/utf8_and_euc_jp \
src/backend/utils/mb/conversion_procs/utf8_and_euc_cn \
src/backend/utils/mb/conversion_procs/utf8_and_cyrillic \
src/backend/utils/mb/conversion_procs/utf8_and_big5 \
src/backend/utils/mb/conversion_procs/utf8_and_ascii \
src/backend/utils/mb/conversion_procs/latin_and_mic \
src/backend/utils/mb/conversion_procs/latin2_and_win1250 \
src/backend/utils/mb/conversion_procs/euc_tw_and_big5 \
src/backend/utils/mb/conversion_procs/euc_kr_and_mic \
src/backend/utils/mb/conversion_procs/euc_jp_and_sjis \
src/backend/utils/mb/conversion_procs/euc_cn_and_mic \
src/backend/utils/mb/conversion_procs/cyrillic_and_mic \
src/backend/utils/mb/conversion_procs/ascii_and_mic \
src/backend/utils/init \
src/backend/utils/hash \
src/backend/utils \
src/backend/utils/fmgr \
src/backend/utils/error \
src/backend/utils/cache \
src/backend/utils/adt \
src/backend/tcop \
src/backend/storage/smgr \
src/backend/storage/page \
src/backend/storage/lmgr \
src/backend/storage/large_object \
src/backend/storage/ipc \
src/backend/storage/freespace \
src/backend/storage/file \
src/backend/storage/buffer \
src/backend/storage \
src/backend/rewrite \
src/backend/regex \
src/backend/postmaster \
src/backend/port \
src/backend/port/win32 \
src/backend/port/tas \
src/backend/port/nextstep \
src/backend/port/dynloader \
src/backend/port/darwin \
src/backend/parser \
src/backend/optimizer/util \
src/backend/optimizer/prep \
src/backend/optimizer/plan \
src/backend/optimizer/path \
src/backend/optimizer/geqo \
src/backend/optimizer \
src/backend/nodes \
src/backend/main \
src/backend/libpq \
src/backend/lib \
src/backend/executor \
src/backend/commands \
src/backend/catalog \
src/backend/bootstrap \
src/backend/access/transam \
src/backend/access/nbtree \
src/backend/access/index \
src/backend/access/heap \
src/backend/access/hash \
src/backend/access/gist \
src/backend/access/gin \
src/backend/access/common \
src/backend/access \
contrib/xml2 \
contrib/vacuumlo \
contrib/tsearch2 \
contrib/tsearch2/wordparser \
contrib/tsearch2/snowball \
contrib/tsearch2/ispell \
contrib/tablefunc \
contrib/sslinfo \
contrib/spi \
contrib/spi/preprocessor \
contrib/seg \
contrib/pgstattuple \
contrib/pgrowlocks \
contrib/pgcrypto \
contrib/pgbench \
contrib/pg_trgm \
contrib/pg_freespacemap \
contrib/pg_buffercache \
contrib/oid2name \
contrib/ltree \
contrib/lo \
contrib/isn \
contrib/intarray \
contrib/intagg \
contrib/hstore \
contrib/fuzzystrmatch \
contrib/earthdistance \
contrib/dblink \
contrib/cube \
contrib/chkpass \
contrib/btree_gist \
contrib/adminpack \

